// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Following []*User `json:"following"`
	Followers []*User `json:"followers"`
}
