// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	ProfileID string `json:"profileId"`
	Body      string `json:"body"`
}

type NewUser struct {
	Email    string `json:"email"`
	Username string `json:"Username"`
}

type Post struct {
	ID        string `json:"id"`
	ProfileID string `json:"profileId"`
	Body      string `json:"body"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"Username"`
}
